version: '3'

services:
  #  app:
  #    build: .
  #    ports:
  #      - "8080:8080"
  #    depends_on:
  #      - db
  #    environment:
  #      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/nursenow
  #      - SPRING_DATASOURCE_USERNAME=postgres
  #      - SPRING_DATASOURCE_PASSWORD=secret

  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nursenow
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
Enfermeiro especializado em cuidados intensivos
Enfermeiro de saúde da família comprometido com o bem-estar dos pacientes
Enfermeiro em hospital de trauma, fornecendo cuidados imediatos e de emergência
Enfermeiro de unidade de terapia intensiva, gerenciando pacientes críticos
Enfermeiro em clínica pediátrica, atendendo crianças com carinho e dedicação
Enfermeiro em centro cirúrgico, garantindo a segurança durante procedimentos
Enfermeiro de saúde mental, prestando apoio emocional e cuidados terapêuticos
Enfermeiro em centro de reabilitação, auxiliando na recuperação dos pacientes
Enfermeiro em casa de repouso, proporcionando cuidados e conforto aos idosos
Enfermeiro em oncologia, acompanhando pacientes durante o tratamento contra o câncer
