spring:
  datasource:
    password: ${JDBC_DATABASE_PASSWORD:password}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/nursenow}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: 'false'

  mvc:
    format:
      time: HH:mm:ss
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd'T'HH:mm:ss

springdoc:
  pathsToMatch: /api/**
