spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/nursenow}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:password}

  messages:
    encoding: ISO-8859-1

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: 'false'

  mvc:
    format:
      time: HH:mm:ss
      date: dd-MM-yyyy
      date-time: HH:mm:ss yyyy-MM-dd

springdoc:
  pathsToMatch: /api/**
