spring:
  datasource:
    password: ${JDBC_DATABASE_PASSWORD:password}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/nursenow}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: 'false'

  mvc:
    format:
      time: HH:mm:ss
      date: dd-MM-yyyy
      date-time: HH:mm:ss yyyy-MM-dd

springdoc:
  pathsToMatch: /api/**
